export class CursosMock {
    static getData() {
        return [
      {
        Id: 1,
        Codigo: "AP122",
        Descripcion: "ORGANIZACI\u00D3N Y DIRECCI\u00D3N DE EMPRESAS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 2,
        Codigo: "CE82",
        Descripcion: "MATEM\u00C1TICA B\u00C1SICA",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 3,
        Codigo: "HE59",
        Descripcion: "ESTRATEGIAS DE REDACCI\u00D3N",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 4,
        Codigo: "IS274",
        Descripcion: "FUNDAMENTOS DE PROGRAMACI\u00D3N 1",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 5,
        Codigo: "IS277",
        Descripcion: "ARQ. DE COMPUTADORAS Y SIST. OPERATIVOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 6,
        Codigo: "CE84",
        Descripcion: "C\u00C1LCULO 1",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 7,
        Codigo: "HE60",
        Descripcion: "ESTRATEGIAS DE COMUNICACI\u00D3N",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 8,
        Codigo: "IS208",
        Descripcion: "DISE\u00D1O DE BASE DE DATOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 9,
        Codigo: "IS275",
        Descripcion: "FUNDAMENTOS DE PROGRAMACI\u00D3N 2",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 10,
        Codigo: "IS278",
        Descripcion: "REDES Y COMUNICACI\u00D3N DE DATOS I",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 11,
        Codigo: "CE85",
        Descripcion: "C\u00C1LCULO 2",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 12,
        Codigo: "CE88",
        Descripcion: "F\u00CDSICA 1",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 1,
      },
      {
        Id: 13,
        Codigo: "HE61",
        Descripcion: "\u00C9TICA Y CIUDADAN\u00CDA",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 14,
        Codigo: "IS207",
        Descripcion: "ESTRUCTURA DE DATOS Y ALGORITMOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 15,
        Codigo: "IS212",
        Descripcion: "IMPLEMENTACI\u00D3N DE BASE DE DATOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 16,
        Codigo: "CE90",
        Descripcion: "F\u00CDSICA 2",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 1,
      },
      {
        Id: 17,
        Codigo: "CE91",
        Descripcion: "MATEM\u00C1TICA DISCRETA",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 18,
        Codigo: "IS255",
        Descripcion: "INGENIER\u00CDA DE REQUERIMIENTOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 19,
        Codigo: "IS282",
        Descripcion: "DISE\u00D1O Y TECNOLOG\u00CDAS UX",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 20,
        Codigo: "CE143",
        Descripcion: "MATEM\u00C1TICA COMPUTACIONAL",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 21,
        Codigo: "CP37",
        Descripcion: "COSTEO DE OPERACIONES",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 22,
        Codigo: "IS211",
        Descripcion: "DESARROLLO PARA ENTORNO WEB",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 23,
        Codigo: "IS254",
        Descripcion: "DISE\u00D1O DE PROCESOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 24,
        Codigo: "IS279",
        Descripcion: "REDES Y COMUNICACI\u00D3N DE DATOS II",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 25,
        Codigo: "CE86",
        Descripcion: "ESTAD\u00CDSTICA APLICADA 1",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 26,
        Codigo: "IS276",
        Descripcion: "PLATAFORMA M\u00D3VILES Y AN\u00C1LISIS CLOUD",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 27,
        Codigo: "IS283",
        Descripcion: "DESARROLLO \u00C1GIL",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 28,
        Codigo: "IS284",
        Descripcion: "FORMULACI\u00D3N Y EVALUACI\u00D3N DE PROYECTOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 29,
        Codigo: "IS221",
        Descripcion: "GERENCIA DE PROYECTOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 30,
        Codigo: "IS281",
        Descripcion: "ANAL\u00CDTICA DE DATOS Y SISTEMAS PREDICTIVOS",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
      {
        Id: 31,
        Codigo: "IS309",
        Descripcion: "ARQUITECTURA EMPRESARIAL",
        Estado: 1,
        HorasSem: 1,
        reqLaboratorio: 0,
      },
    ]
    }
}